version: '3.8'
services:
  postgres:
    image: postgres
    container_name: savepoint_container
    environment:
      POSTGRES_DB: savepoint
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"
    restart: always
